#!/usr/bin/env python3
"""Build the Unity API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Push Notifications': 'Push Notif.',
    'Cloud Content': 'Cloud CDN',
    'UGC': 'UGC',
    'Build Automation': 'Build Auto',
    'Asset Manager': 'Asset Mgr',
    'Multiplay': 'Multiplay GS',
    'Distributed Auth': 'Dist. Auth',
    'Version Control': 'Version Ctrl',
    'Player Auth': 'Player Auth',
}

LINES = [
    {
        "name": 'Live Operations',
        "color": '#000000',
        "stations": [
        ('Cloud Code', (270, 195)),
        ('Cloud Save', (430, 175)),
        ('Economy', (580, 165)),
        ('Leaderboards', (730, 175)),
        ('Remote Config', (890, 195)),
        ('Analytics', (1030, 220)),
        ],
    },
    {
        "name": 'Multiplayer',
        "color": '#1E5BD0',
        "stations": [
        ('Lobby', (270, 310)),
        ('Matchmaker', (420, 285)),
        ('Relay', (580, 285)),
        ('Multiplay', (740, 285)),
        ('Distributed Auth', (910, 285)),
        ],
    },
    {
        "name": 'Player & Auth',
        "color": '#0E9D6E',
        "stations": [
        ('Player Auth', (270, 430)),
        ('Friends', (440, 410)),
        ('Vivox', (610, 410)),
        ('Moderation', (790, 410)),
        ('Push Notifications', (960, 430)),
        ],
    },
    {
        "name": 'Content & Build',
        "color": '#E68B1F',
        "stations": [
        ('Cloud Content', (270, 555)),
        ('UGC', (470, 530)),
        ('Build Automation', (650, 530)),
        ('Version Control', (840, 530)),
        ('Asset Manager', (1010, 555)),
        ],
    },
    {
        "name": 'Identity & Misc',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Access', (640, 670)),
        ('SCIM', (790, 740)),
        ('Triggers', (740, 815)),
        ('Scheduler', (540, 815)),
        ('Safe Text', (490, 740)),
        ('Monetize', (640, 815)),
        ],
    },
]

URL_OVERRIDES = {
    'Player Auth': 'https://apis.apis.io/apis/unity/player-authentication/',
    'Cloud Code': 'https://apis.apis.io/apis/unity/cloud-code/',
    'Cloud Save': 'https://apis.apis.io/apis/unity/cloud-save/',
    'Economy': 'https://apis.apis.io/apis/unity/economy/',
    'Leaderboards': 'https://apis.apis.io/apis/unity/leaderboards/',
    'Remote Config': 'https://apis.apis.io/apis/unity/remote-config/',
    'Analytics': 'https://apis.apis.io/apis/unity/analytics/',
    'Lobby': 'https://apis.apis.io/apis/unity/lobby/',
    'Matchmaker': 'https://apis.apis.io/apis/unity/matchmaker/',
    'Relay': 'https://apis.apis.io/apis/unity/relay/',
    'Multiplay': 'https://apis.apis.io/apis/unity/multiplay-game-server-hosting/',
    'Cloud Content': 'https://apis.apis.io/apis/unity/cloud-content-delivery/',
    'Triggers': 'https://apis.apis.io/apis/unity/triggers/',
    'Scheduler': 'https://apis.apis.io/apis/unity/scheduler/',
    'Friends': 'https://apis.apis.io/apis/unity/friends/',
    'Vivox': 'https://apis.apis.io/apis/unity/vivox/',
    'Moderation': 'https://apis.apis.io/apis/unity/moderation/',
    'UGC': 'https://apis.apis.io/apis/unity/user-generated-content/',
    'Push Notifications': 'https://apis.apis.io/apis/unity/push-notifications/',
    'Build Automation': 'https://apis.apis.io/apis/unity/build-automation/',
    'Version Control': 'https://apis.apis.io/apis/unity/version-control/',
    'Access': 'https://apis.apis.io/apis/unity/access/',
    'SCIM': 'https://apis.apis.io/apis/unity/scim/',
    'Distributed Auth': 'https://apis.apis.io/apis/unity/distributed-authority/',
    'Safe Text': 'https://apis.apis.io/apis/unity/safe-text/',
    'Asset Manager': 'https://apis.apis.io/apis/unity/asset-manager/',
    'Monetize': 'https://apis.apis.io/apis/unity/monetize/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Unity API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: unity/openapi · github.com/api-evangelist/unity',
        out_dir=Path(__file__).resolve().parent,
        out_basename='unity-subway-map',
        provider_id='unity',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
